### ISSUE TITLE
[Feature]: Fix missing some johnea/mysql image from Docker Hub

### ISSUE THREAD

**Issue by BoGnY** [john-ea/devilbox#5]
### What is your idea or feature suggestion?

There are many missing images for 0.23 version:
- mariadb 10.7
- mariadb 10.8
- mariadb 10.9
- mariadb 10.10

### Are you willing to provide a PR to address this?

None

**Comment by john-ea** [comment]
I have not officially added docker-mysql 0.23 version images to Devilbox Release v3.0.0-beta-0.5, as it must pass the tests first.
And also for the End-of-life (EOL) versions, there was a build only on a schedule once a month. Now I've changed it to weekly, as well as automatic build upon release.

Mysql images 0.23 version added only today in Devilbox Release v3.0.0-beta-0.6

**Comment by BoGnY** [comment]
oh ok, I didn't see that versions are EOL
